### ISSUE TITLE
Graphs for homebuilt machine not working

### ISSUE THREAD

**Issue by hexadecagram** [seren/freenas-temperature-graphing#10]
Like the title says, I have a homebuilt FreeNAS machine that isn't generating graphs correctly.

The machine is a Shuttle DH170 with an i7-6700 processor and the following drives, as reported by `smartctl -i`:

/dev/ada0: TS512GMTS600 (Transcend MTS600 512GB M.2 SSD)
/dev/ada1: Samsung 850 PRO 512GB SATA SSD
/dev/da0: Raritan virtual USB device that does not require graphing, and is currently skipped as it should be

First of all, the CPU graph always looks similar to [this.](https://pasteboard.co/GF4v8nx.png)

The [drive graph](https://pasteboard.co/GF4vljq.png) is just completely blank even though ada0 is listed in the legend.

I've taken a quick look at rrd.sh and see that data is collected by running `smartctl -a` on the device, which is piped through a couple of awk commands (line 225). If I run those commands on the console for each device in turn, I see this:

```
# /usr/local/sbin/smartctl -a /dev/ada0 | awk '/194 Temperature_Celsius/{print $0}' | awk '{print $10}'
51
# /usr/local/sbin/smartctl -a /dev/ada1 | awk '/194 Temperature_Celsius/{print $0}' | awk '{print $10}'
```

As you can see, /dev/ada0 gets the correct output but /dev/ada1 generates no output.

So I ran this:

```
# smartctl -a /dev/ada1 | grep Temp
190 Airflow_Temperature_Cel 0x0032   064   048   000    Old_age   Always       -       36
```

Lo and behold, the second drive is reporting its temperature under a different label. So, I modified line 225 as follows (which I tested on the command line and got values for both drives):

```
DevTemp=`/usr/local/sbin/smartctl -a /dev/$i | awk '/Temperature_C/{print $10}'`
```

I then deleted temps-5min.rrd and waited for the cron jobs to re-run. After doing so, I immediately notice that ada0 is still the only drive being listed in the legend; no sign of ada1. The CPU graph shows all 8 cores in the legend. Five minutes later, I get an email saying:

> ERROR: /root/freenas-temperature-graphing/temps-5min.rrd: expected 10 data source readings (got 9) from N

Next I run this:

```
# ./rrd.sh -v temps-1min.rrd
Rrdtool database filename: temps-1min.rrd
Current working directory is: /root/freenas-temperature-graphing
Rrdtool database doesn't exist. Creating it.
numcpus: 8
drivedevs:  ada0
numcpus: 8
drivedevs:  ada0 ada1
numcpus: 8
drivedevs:  ada0 ada1
Sampling every 60 seconds
Creating rrdtool db file: temps-1min.rrd
Rrdtool arguments:   DS:cpu0:GAUGE:120:0:150 DS:cpu1:GAUGE:120:0:150 DS:cpu2:GAUGE:120:0:150 DS:cpu3:GAUGE:120:0:150 DS:cpu4:GAUGE:120:0:150 DS:cpu5:GAUGE:120:0:150 DS:cpu6:GAUGE:120:0:150 DS:cpu7:GAUGE:120:0:150 DS:ada0:GAUGE:120:0:100 DS:ada1:GAUGE:120:0:100                                              /usr/local/bin/rrdtool create temps-1min.rrd --step 60 DS:cpu0:GAUGE:120:0:150 DS:cpu1:GAUGE:120:0:150 DS:cpu2:GAUGE:120:0:150 DS:cpu3:GAUGE:120:0:150 DS:cpu4:GAUGE:120:0:150 DS:cpu5:GAUGE:120:0:150 DS:cpu6:GAUGE:120:0:150 DS:cpu7:GAUGE:120:0:150 DS:ada0:GAUGE:120:0:100 DS:ada1:GAUGE:120:0:100 RRA:MAX:0.5:1:3000
Initialized datafile
```

Then it occurs to me that da0 might be screwing up the data collection because it doesn't report any S.MA.R.T. data (and I have to add `-d scsi` to get it to display anything at all):

```
# smartctl -d scsi -a /dev/da0
smartctl 6.5 2016-05-07 r4318 [FreeBSD 11.0-STABLE amd64] (local build)
Copyright (C) 2002-16, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF INFORMATION SECTION ===
Vendor:               Generic
Product:              STORAGE DEVICE
Revision:             0208
Device type:          disk
Local Time is:        Thu Aug 10 17:09:20 2017 PDT
NO MEDIUM present in device
A mandatory SMART command failed: exiting. To continue, add one or more '-T permissive' options.
```

After expecting rrd.sh closer, it seems that the sanity check on line 226 is failing. A better way to write that block would be as follows:

```
  for i in $(/sbin/sysctl -n kern.disks | grep da); do
    # Sanity check that the drive will return a temperature (we don't want to include non-SMART usb devices)
    DevTemp=`/usr/local/sbin/smartctl -a /dev/"${i}" | awk '/Temperature_C/{print $10}'`
    if [ -n "$DevTemp" ]; then
      drivedevs="${drivedevs} ${i}"
      [ -n "$verbose" ] && echo "drivedevs: ${drivedevs}"
    fi
  done
  [ -n "$verbose" ] && echo "numcpus: ${numcpus}"
```

Notice I replaced 2 `awk`'s with 1 `grep` and moved the verbose output for drivedevs into that block, because we're only interested if they are **_added_** with each loop. Also, numcpus doesn't belong anywhere in that loop.

Then I run `rm temps-1min.rrd`, re-run `rrd.sh -v temps-1min.rrd` and see this, which seems like a step in the right direction:

```
drivedevs:  ada0
drivedevs:  ada0 ada1
numcpus: 8
```

Unfortunately, the drives graph still only has ada0 in the legend, I am still receiving an email saying that only 9 data source readings are successful, and I am still not seeing anything at all in my CPU graphs. So I have a look at rrd-graph.sh, and I see something very similar, beginning at line 109. So I change that block to match:

```
# Get drive device names
drivedevs=
for i in $(/sbin/sysctl -n kern.disks | grep da); do
  # Sanity check that the drive will return a temperature (we don't want to include non-SMART usb devices)
  DevTemp=$(/usr/local/sbin/smartctl -a /dev/"${i}" | awk '/Temperature_C/{print $10}');
  if [ -n "$DevTemp" ]; then
    drivedevs="${drivedevs} ${i}"
    [ -n "$verbose" ] && echo "drivedevs: ${drivedevs}"
  fi
done
[ -n "$verbose" ] && echo "numcpus: ${numcpus}"
```

Now I am seeing ada0 and ada1 in the legend for the drive graphs but I'm still getting errors about data source readings. I thought that this was due to another bug in rrd.sh but it turns out its in temps-rrd-format.sh in two places, starting at line 66, which I modify as follows:

```
# Get drive device names
drivedevs=
for i in $(/sbin/sysctl -n kern.disks | grep da); do
  # Sanity check that the drive will return a temperature (we don't want to include non-SMART usb devices)
  DevTemp=`/usr/local/sbin/smartctl -a /dev/"$i" | awk '/Temperature_C/{print $10}'`
  if [ -n "$DevTemp" ]; then on line 81
    drivedevs="${drivedevs} ${i}"
    [ -n "$verbose" ] && echo "drivedevs: ${drivedevs}"
  fi
done
[ -n "$verbose" ] && echo "numcpus: ${numcpus}"
```

And at line 80, which I modify as follows:

```
# Get drive temperatures
for i in ${drivedevs}; do
  DevTemp=`/usr/local/sbin/smartctl -a /dev/$i | awk '/Temperature_C/{print $10}'`;
  if [ -n "$DevTemp" ]; then
    data="${data}${sep}${DevTemp}"
  fi
done
[ -n "$verbose" ] && echo "Raw data: ${data}"
```

After those modifications are made, both rrd.sh and rrd-graph.sh exit without error when I run them on the command line (and I am no longer receiving emails from FreeNAS).

After a few minutes, I start seeing graphs again. However, I only see one drive on the drive graph. This is because ada0 is currently operating at 53 degrees Celsius.

Most SSD manufacturers state that 0 to 70 degrees Celsius are safe operating temperatures. The WD Red drives that iXsystems ships with their FreeNAS Minis recommend 0-65. And the only other mechanical drive I have (HGST Travelstar) is listed as 0-60.

It's probably also worth noting that SAFETEMPLINE only applies if the drive is mechanical. SSDs will ["thermally throttle" based on temperature,](https://www.reddit.com/r/DataHoarder/comments/5foym3/safe_max_temp_for_ssd_in_terms_of_reliability/) so most any temperature below 70 is fine for SSDs.

In the case of mechanical drives, [according to Google, the ideal temperature range is between 37 and 46.](https://en.wikibooks.org/wiki/Minimizing_Hard_Disk_Drive_Failure_and_Data_Loss/Environmental_Control)

It might be worth having lines for both of those temperature limits because having a cold (again, **_mechanical_**) drive is just as bad if not worse than a hot one. Some sort of note about those limits only applying to mechanical drives should probably be made in the graph, if possible. I went ahead and added that in to rrd-graph.sh.

At any rate, once I change the MAXGRAPHTEMP variable on line 81 in rrd-graph.sh from 50 to 70, I see [graphs for both drives.](https://pasteboard.co/GF5BzAV.png)

Now, onto the CPU graph.

It doesn't look nearly as bad as it did however it's [quite unreadable, at least for the 1min graph.](https://pasteboard.co/GF5AftM.png) That's some wild variation for a machine that is sitting idle! [Here's my other **_highly_** active server](https://pasteboard.co/GF5D4AK.png) for comparison. The former has CPU load 0.09/0.13/0.14 and the latter is at 3.18/2.60/2.49 and pushing 200-250 Mbps of NFS almost constantly.

If I delete the line containing `--slope-mode` from rrd-graph.sh at line 131, [the lines are much clearer.](https://pasteboard.co/GF5KDhK.png) That still doesn't explain why this machine is seeing +/- 5 degrees Celsius while the other is seeing +/- 2 at most, but that's nothing to do with freenas-temperature-graphing, I'm sure.

I've pushed up all the edits for this ticket and generated a pull request.

**Comment by seren** [comment]
Thanks for the PR and detailed write-up. I'll take a look later today.

**Comment by seren** [comment]
I like most of your changes, and apologize for the duplication of code. There are few comments I made regarding problems with the awk changes, but otherwise everything looks good. I may change the safe-temperature line and graph scale logic down the road so that it makes sense for people with only SSDs, only magnetic drives, or both.

I actually started DRYing up the scripts and breaking out the reused bits into functions. If you address the comments, I'll merge your changes and then incorporate them into the non-redundant new version. Then any future bugs should only have to be fixed in one place. :)

**Comment by hexadecagram** [comment]
I'm not seeing any comments. Did you forget to commit them to my fork?

**Comment by seren** [comment]
Ahh, I was actually doing in the github interface: https://github.com/seren/freenas-temperature-graphing/pull/11/files#diff-fc4c73a813916433778e1ddded254b3dL111

Do they show up for you?

**Comment by hexadecagram** [comment]
No I'm afraid I do not see your changes, just my own changes.

**Comment by seren** [comment]
I just tried submitting a review (sorry, still new to this aspect of github) and I think they're showing up now. It seems you do all the comments and then submit them in a review.

**Comment by seren** [comment]
I added a few commits after merging your changes. I figured I'd let you know here. They are:
* Restore the ascending order for disk devices, so that people's existing graphs don't get messed up (efa846e9085cb24dd62e985e069aa6bb10a6e326)
* Add the awk script changes we talked about (4637338b134a2692fcfceab50611710118dff00d)
* I prefer using absolute paths when calling internal libraries, and since we already were deriving the script directory (CWD), I replaced the path modifications (3d6a057824eb341f546056f8fe80ecf8661e1550)
