### ISSUE TITLE
SpaceCabbie

### ISSUE THREAD

**Issue by spacecabbie** [seren/freenas-temperature-graphing#14]
Hi i get this issue ERROR:  is not a vname nor a number
ERROR:  is not a vname nor a number
ERROR:  is not a vname nor a number
ERROR:  is not a vname nor a number
ERROR:  is not a vname nor a number
ERROR:  is not a vname nor a number
ERROR:  is not a vname nor a number
ERROR:  is not a vname nor a number

also the script only reports all drives in one graph even though i uncommented the all drives sections the all cpus section is working graphs are being madeper cpu. I presume the above error are connected  Any sugggestions ?

**Comment by seren** [comment]
Could you try running the commands manually and see if it's the rrd.sh or rrd-graph.sh script that's having the problem? Once you know, try adding `-d` to the command to get debugging output and post it here (with triple back-ticks so it's readable, please). Example with `-d`:

`/mnt/poolname/temps-directory/rrd.sh /mnt/poolname/temps-directory/temps-1min.rrd -d`

**Comment by spacecabbie** [comment]
```
ERROR:  is not a vname nor a number
ERROR:  is not a vname nor a number
ERROR:  is not a vname nor a number
ERROR:  is not a vname nor a number
ERROR:  is not a vname nor a number
ERROR:  is not a vname nor a number
ERROR:  is not a vname nor a number
ERROR:  is not a vname nor a number
```
Just that error this is manual  output with the -d  I have narrowed it down its indeed the last part of the script:
```
# Output graphs of each drive
for drdev in ${drivedevs}; do
  defsandlines="DEF:${drdev}=${datafile}:${i}:MAX LINE1:${i}#000000:\"${i}\""
  outputfilename=drive-${drdev}
  guidrule="HRULE:${SAFETEMPLINE}#FF0000"
  title="Temperature: Drive ${drdev}, ${interval} minute interval"
  write_graph_to_disk
done'
```
When this part is commented like originally: 
```
# # Output graphs of each drive
# for drdev in ${drivedevs}; do
#   defsandlines="DEF:${drdev}=${datafile}:${i}:MAX LINE1:${i}#000000:\"${i}\""
#   outputfilename=drive-${drdev}
#   guidrule="HRULE:${SAFETEMPLINE}#FF0000"
#   title="Temperature: Drive ${drdev}, ${interval} minute interval"
#   write_graph_to_disk
# done
```
There is no error.

The problem then is in the last part of rrd-graph.sh

Thanks for the speedy response btw.

**Comment by seren** [comment]
I think I've fixed it. Feel free to reopen if not.

**Comment by spacecabbie** [comment]
Am Afraid not. exact same error tried the debug again din't get any extra information for you unfortunately.
I am available for testing if need be tomorrow.
No clue how to reopen though. Btw again thanks for the quick support ! 👍

**Comment by seren** [comment]
Hmm, strange. Can you edit your `rrd-graph.sh` file and insert a line just below the first line:
`set -x`

This will cause the script to output everything as it runs. Could you also post the exact command line you're using to run the script?

**Comment by spacecabbie** [comment]
Sure be happy to here are the results:
https://pastebin.com/SCjg5MgF

exact command:
```
/mnt/BlackHole/Storage/Freenas_Scripts/freenas-temperature-graphing-master/rrd-graph.sh /mnt/BlackHole/Storage/Freenas_Scripts/freenas-temperature-graphing-master/temps-5min.rrd -d
```

**Comment by seren** [comment]
Ok, I think it's really fixed this time, as well as `-d` not working when it's the last argument. I've also changed the code a bit, so now you only have to uncomment a line at the bottom of `rrd-graph.sh`.

**Comment by spacecabbie** [comment]
Love the changes works like a charm do you know if there is any way to "hack this in the interface of freenas ?"

**Comment by seren** [comment]
There's a discussion about that in #12
