### ISSUE TITLE
Unable to setup

### ISSUE THREAD

**Issue by nirretorsten** [seren/freenas-temperature-graphing#2]
Hello. I cant get the scripts to work. It seemed kind of straight forward but i get an error. And yes im not the best with codes and such.

"ERROR: Cannot chmod temporary file!
 ERROR: opening '/mnt/SingleDisk/Extra/temp-monitor/temps-1min.rrd': No such file or directory"
[namnlos](https://cloud.githubusercontent.com/assets/3535191/15854612/0cd5728c-2cab-11e6-89f4-569f1a8b280c.png)

**Comment by seren** [comment]
If you log into the console and run this manually: `/mnt/SingleDisk/Extra/temp-monitor/rrd.sh /mnt/SingleDisk/Extra/temp-monitor/temps-1min.rrd` do you get any errors?

**Comment by nirretorsten** [comment]
Still get the same error.
![error](https://cloud.githubusercontent.com/assets/3535191/15861690/6afc76fe-2ccd-11e6-987c-9efc79f4814a.png)

**Comment by seren** [comment]
Sorry for the slow reply. Could you add "set -x" to the script as the 2nd line and run it again?

**Comment by JoeB99** [comment]
I have the same issue. Here is the output <cropped> with set -x added into the rrd.sh file (2nd line down).

ERROR: Cannot chmod temporary file!
++ /mnt/vol1/Backup/freenas-temperature-graphing/temps-rrd-format.sh
+ data=59:59:30:29:28:28:33:36
+ /usr/local/bin/rrdtool update /mnt/vol1/Backup/freenas-temperature-graphing/temps-1min.rrd N:59:59:30:29:28:28:33:36
ERROR: opening '/mnt/vol1/Backup/freenas-temperature-graphing/temps-1min.rrd': No such file or directory

**Comment by Marthym** [comment]
@nirretorsten Maybe you need to create directory :

`mkdir -p /mnt/SingleDisk/Extra/temp-monitor`

If the cron for the graph generation start before the cron for collecting data this error is normal for the first run.

**Comment by whinette** [comment]
Resolved: root did not have rights.

**Comment by seren** [comment]
@whinette Thanks for the update.

**Comment by seren** [comment]
I'm closing this since due to lack of response by the original poster.
