### ISSUE TITLE
temps-rrd-format.sh line 85 has no closing quote.

### ISSUE THREAD

**Issue by ingestre** [seren/freenas-temperature-graphing#6]
Line currently reads 
[ -n $verbose ] && echo "Cleaned up data:

In addition please pay attention to the use of quotes with the -n test operator. From the manual...

The -n test requires that the string be quoted within the test brackets. Using an unquoted string with ! -z, or even just the unquoted string alone within test brackets normally works, however, this is an unsafe practice. Always quote a tested string

**Comment by seren** [comment]
Thanks for catching that.
