### ISSUE TITLE
Applying a licence

### ISSUE THREAD

**Issue by davidjb** [seren/freenas-temperature-graphing#8]
Thanks for sharing this open-source code.  I'm interested in reusing your work but it doesn't appear as through your repo has a licence at present.  Would you consider adding one?  This would help clarify any ambiguity around rights.  

https://choosealicense.com/ is a GitHub-maintained helper for choosing, if you don't already have something in mind.

Thanks!

**Comment by seren** [comment]
Thanks for pointing that out. I've added Unlicense licensing.

**Comment by davidjb** [comment]
Thank you very much!
